language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6.11.0
  - 0.8.1.1
before_install:
  - npm install -g

script: npm test

notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky